server.port=8082
server.servlet.context-path=/address
#eureka.client.service-url.defaultZone=
management.endpoints.web.exposure.include=*
#eureka.client.service-url.defaultZone=http://eureka-server-app-svc:8761/eureka
#Here we removed eureka because we are going to user kubernetes inernal registry
