server.port=8081
server.servlet.context-path=/employee
addressservice.context-path=/address
eureka.client.service-url.defaultZone=http://eureka-server-app-svc:8761/eureka
#addressservice.base.url=http://localhost:8082/address
#eureka.client.service-url.defaultZone=
