#gateway webflux is using netty server, so it is not picking these config. Use local property files.
server.port=8888
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Here we removed eureka because we are going to user kubernetes inernal registry

management.endpoints.web.exposure.include=*
logging.level.org.springframework.gateway=DEBUG
management.endpoint.gateway.access=read-only
spring.cloud.gateway.metrics.enabled=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id: employee-service
spring.cloud.gateway.routes[0].uri: http://employee-service-app-svc:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**

spring.cloud.gateway.routes[1].id: address-service
spring.cloud.gateway.routes[1].uri: http://address-service-app-svc:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/address/**

